//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the gazebo_tests package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __gazebo_tests__MODELSPAWNCONFIG_H__
#define __gazebo_tests__MODELSPAWNCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace gazebo_tests
{
  class ModelSpawnConfigStatics;

  class ModelSpawnConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(ModelSpawnConfig &config, const ModelSpawnConfig &max, const ModelSpawnConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const ModelSpawnConfig &config1, const ModelSpawnConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, ModelSpawnConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const ModelSpawnConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ModelSpawnConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const ModelSpawnConfig &config) const = 0;
      virtual void getValue(const ModelSpawnConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T ModelSpawnConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T ModelSpawnConfig::* field;

      virtual void clamp(ModelSpawnConfig &config, const ModelSpawnConfig &max, const ModelSpawnConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const ModelSpawnConfig &config1, const ModelSpawnConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, ModelSpawnConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const ModelSpawnConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ModelSpawnConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const ModelSpawnConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const ModelSpawnConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, ModelSpawnConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, ModelSpawnConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<ModelSpawnConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(ModelSpawnConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("MODELNAME_"==(*_i)->name){MODELNAME_ = boost::any_cast<std::string>(val);}
        if("MASS_"==(*_i)->name){MASS_ = boost::any_cast<double>(val);}
        if("IXYZ_"==(*_i)->name){IXYZ_ = boost::any_cast<double>(val);}
        if("SIZEX_"==(*_i)->name){SIZEX_ = boost::any_cast<double>(val);}
        if("SIZEY_"==(*_i)->name){SIZEY_ = boost::any_cast<double>(val);}
        if("SIZEZ_"==(*_i)->name){SIZEZ_ = boost::any_cast<double>(val);}
        if("RESTITUTION_COEFFICIENT_"==(*_i)->name){RESTITUTION_COEFFICIENT_ = boost::any_cast<double>(val);}
        if("THRESHOLD_"==(*_i)->name){THRESHOLD_ = boost::any_cast<int>(val);}
        if("MU_"==(*_i)->name){MU_ = boost::any_cast<double>(val);}
        if("MU2_"==(*_i)->name){MU2_ = boost::any_cast<double>(val);}
        if("FDIR1X_"==(*_i)->name){FDIR1X_ = boost::any_cast<int>(val);}
        if("FDIR1Y_"==(*_i)->name){FDIR1Y_ = boost::any_cast<int>(val);}
        if("FDIR1Z_"==(*_i)->name){FDIR1Z_ = boost::any_cast<int>(val);}
        if("SLIP1_"==(*_i)->name){SLIP1_ = boost::any_cast<double>(val);}
        if("SLIP2_"==(*_i)->name){SLIP2_ = boost::any_cast<double>(val);}
        if("SOFT_CFM_"==(*_i)->name){SOFT_CFM_ = boost::any_cast<double>(val);}
        if("SOFT_ERP_"==(*_i)->name){SOFT_ERP_ = boost::any_cast<double>(val);}
        if("KP_"==(*_i)->name){KP_ = boost::any_cast<double>(val);}
        if("KD_"==(*_i)->name){KD_ = boost::any_cast<double>(val);}
        if("MINDEPTH_"==(*_i)->name){MINDEPTH_ = boost::any_cast<double>(val);}
        if("MAXVEL_"==(*_i)->name){MAXVEL_ = boost::any_cast<double>(val);}
        if("VELDECAYLINEAR_"==(*_i)->name){VELDECAYLINEAR_ = boost::any_cast<double>(val);}
        if("VELDECAYANGULAR_"==(*_i)->name){VELDECAYANGULAR_ = boost::any_cast<double>(val);}
        if("click_to_spawn_model"==(*_i)->name){click_to_spawn_model = boost::any_cast<bool>(val);}
        if("DEGREESRAMP"==(*_i)->name){DEGREESRAMP = boost::any_cast<double>(val);}
        if("MURAMP_"==(*_i)->name){MURAMP_ = boost::any_cast<double>(val);}
        if("MU2RAMP_"==(*_i)->name){MU2RAMP_ = boost::any_cast<double>(val);}
        if("FDIR1XRAMP_"==(*_i)->name){FDIR1XRAMP_ = boost::any_cast<int>(val);}
        if("FDIR1YRAMP_"==(*_i)->name){FDIR1YRAMP_ = boost::any_cast<int>(val);}
        if("FDIR1ZRAMP_"==(*_i)->name){FDIR1ZRAMP_ = boost::any_cast<int>(val);}
        if("SLIP1RAMP_"==(*_i)->name){SLIP1RAMP_ = boost::any_cast<double>(val);}
        if("SLIP2RAMP_"==(*_i)->name){SLIP2RAMP_ = boost::any_cast<double>(val);}
        if("SOFT_CFMRAMP_"==(*_i)->name){SOFT_CFMRAMP_ = boost::any_cast<double>(val);}
        if("SOFT_ERPRAMP_"==(*_i)->name){SOFT_ERPRAMP_ = boost::any_cast<double>(val);}
        if("KPRAMP_"==(*_i)->name){KPRAMP_ = boost::any_cast<double>(val);}
        if("KDRAMP_"==(*_i)->name){KDRAMP_ = boost::any_cast<double>(val);}
        if("MINDEPTHRAMP_"==(*_i)->name){MINDEPTHRAMP_ = boost::any_cast<double>(val);}
        if("MAXVELRAMP_"==(*_i)->name){MAXVELRAMP_ = boost::any_cast<double>(val);}
        if("click_to_spawn_ramp"==(*_i)->name){click_to_spawn_ramp = boost::any_cast<bool>(val);}
      }
    }

    std::string MODELNAME_;
double MASS_;
double IXYZ_;
double SIZEX_;
double SIZEY_;
double SIZEZ_;
double RESTITUTION_COEFFICIENT_;
int THRESHOLD_;
double MU_;
double MU2_;
int FDIR1X_;
int FDIR1Y_;
int FDIR1Z_;
double SLIP1_;
double SLIP2_;
double SOFT_CFM_;
double SOFT_ERP_;
double KP_;
double KD_;
double MINDEPTH_;
double MAXVEL_;
double VELDECAYLINEAR_;
double VELDECAYANGULAR_;
bool click_to_spawn_model;
double DEGREESRAMP;
double MURAMP_;
double MU2RAMP_;
int FDIR1XRAMP_;
int FDIR1YRAMP_;
int FDIR1ZRAMP_;
double SLIP1RAMP_;
double SLIP2RAMP_;
double SOFT_CFMRAMP_;
double SOFT_ERPRAMP_;
double KPRAMP_;
double KDRAMP_;
double MINDEPTHRAMP_;
double MAXVELRAMP_;
bool click_to_spawn_ramp;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string MODELNAME_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double MASS_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double IXYZ_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double SIZEX_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double SIZEY_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double SIZEZ_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double RESTITUTION_COEFFICIENT_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int THRESHOLD_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double MU_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double MU2_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int FDIR1X_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int FDIR1Y_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int FDIR1Z_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double SLIP1_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double SLIP2_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double SOFT_CFM_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double SOFT_ERP_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double KP_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double KD_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double MINDEPTH_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double MAXVEL_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double VELDECAYLINEAR_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double VELDECAYANGULAR_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool click_to_spawn_model;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double DEGREESRAMP;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double MURAMP_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double MU2RAMP_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int FDIR1XRAMP_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int FDIR1YRAMP_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int FDIR1ZRAMP_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double SLIP1RAMP_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double SLIP2RAMP_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double SOFT_CFMRAMP_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double SOFT_ERPRAMP_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double KPRAMP_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double KDRAMP_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double MINDEPTHRAMP_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double MAXVELRAMP_;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool click_to_spawn_ramp;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("ModelSpawnConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const ModelSpawnConfig &__max__ = __getMax__();
      const ModelSpawnConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const ModelSpawnConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const ModelSpawnConfig &__getDefault__();
    static const ModelSpawnConfig &__getMax__();
    static const ModelSpawnConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const ModelSpawnConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void ModelSpawnConfig::ParamDescription<std::string>::clamp(ModelSpawnConfig &config, const ModelSpawnConfig &max, const ModelSpawnConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class ModelSpawnConfigStatics
  {
    friend class ModelSpawnConfig;

    ModelSpawnConfigStatics()
    {
ModelSpawnConfig::GroupDescription<ModelSpawnConfig::DEFAULT, ModelSpawnConfig> Default("Default", "", 0, 0, true, &ModelSpawnConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MODELNAME_ = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MODELNAME_ = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MODELNAME_ = "test_model";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<std::string>("MODELNAME_", "str", 0, "model name of the box", "", &ModelSpawnConfig::MODELNAME_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<std::string>("MODELNAME_", "str", 0, "model name of the box", "", &ModelSpawnConfig::MODELNAME_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MASS_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MASS_ = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MASS_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("MASS_", "double", 0, "box mass", "", &ModelSpawnConfig::MASS_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("MASS_", "double", 0, "box mass", "", &ModelSpawnConfig::MASS_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.IXYZ_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.IXYZ_ = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.IXYZ_ = 0.01;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("IXYZ_", "double", 0, "inertia ixx, iyy, izz terms", "", &ModelSpawnConfig::IXYZ_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("IXYZ_", "double", 0, "inertia ixx, iyy, izz terms", "", &ModelSpawnConfig::IXYZ_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.SIZEX_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.SIZEX_ = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.SIZEX_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SIZEX_", "double", 0, "box size and collision X", "", &ModelSpawnConfig::SIZEX_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SIZEX_", "double", 0, "box size and collision X", "", &ModelSpawnConfig::SIZEX_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.SIZEY_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.SIZEY_ = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.SIZEY_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SIZEY_", "double", 0, "box size and collision Y", "", &ModelSpawnConfig::SIZEY_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SIZEY_", "double", 0, "box size and collision Y", "", &ModelSpawnConfig::SIZEY_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.SIZEZ_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.SIZEZ_ = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.SIZEZ_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SIZEZ_", "double", 0, "box size and collision Z", "", &ModelSpawnConfig::SIZEZ_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SIZEZ_", "double", 0, "box size and collision Z", "", &ModelSpawnConfig::SIZEZ_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.RESTITUTION_COEFFICIENT_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.RESTITUTION_COEFFICIENT_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.RESTITUTION_COEFFICIENT_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("RESTITUTION_COEFFICIENT_", "double", 0, "bounce restitution coefficient", "", &ModelSpawnConfig::RESTITUTION_COEFFICIENT_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("RESTITUTION_COEFFICIENT_", "double", 0, "bounce restitution coefficient", "", &ModelSpawnConfig::RESTITUTION_COEFFICIENT_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.THRESHOLD_ = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.THRESHOLD_ = 1000000000;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.THRESHOLD_ = 100000;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<int>("THRESHOLD_", "int", 0, "bounce threshold", "", &ModelSpawnConfig::THRESHOLD_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<int>("THRESHOLD_", "int", 0, "bounce threshold", "", &ModelSpawnConfig::THRESHOLD_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MU_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MU_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MU_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("MU_", "double", 0, "mu, Coefficient of friction", "", &ModelSpawnConfig::MU_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("MU_", "double", 0, "mu, Coefficient of friction", "", &ModelSpawnConfig::MU_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MU2_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MU2_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MU2_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("MU2_", "double", 0, "mu2, Second coefficient of friction", "", &ModelSpawnConfig::MU2_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("MU2_", "double", 0, "mu2, Second coefficient of friction", "", &ModelSpawnConfig::MU2_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FDIR1X_ = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FDIR1X_ = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FDIR1X_ = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<int>("FDIR1X_", "int", 0, "fdir1 X, direction of mu1 in the collision local reference frame", "", &ModelSpawnConfig::FDIR1X_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<int>("FDIR1X_", "int", 0, "fdir1 X, direction of mu1 in the collision local reference frame", "", &ModelSpawnConfig::FDIR1X_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FDIR1Y_ = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FDIR1Y_ = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FDIR1Y_ = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<int>("FDIR1Y_", "int", 0, "fdir1 Y, direction of mu1 in the collision local reference frame", "", &ModelSpawnConfig::FDIR1Y_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<int>("FDIR1Y_", "int", 0, "fdir1 Y, direction of mu1 in the collision local reference frame", "", &ModelSpawnConfig::FDIR1Y_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FDIR1Z_ = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FDIR1Z_ = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FDIR1Z_ = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<int>("FDIR1Z_", "int", 0, "fdir1 Z, direction of mu1 in the collision local reference frame", "", &ModelSpawnConfig::FDIR1Z_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<int>("FDIR1Z_", "int", 0, "fdir1 Z, direction of mu1 in the collision local reference frame", "", &ModelSpawnConfig::FDIR1Z_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.SLIP1_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.SLIP1_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.SLIP1_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SLIP1_", "double", 0, "slip1, force dependent slip direction 1", "", &ModelSpawnConfig::SLIP1_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SLIP1_", "double", 0, "slip1, force dependent slip direction 1", "", &ModelSpawnConfig::SLIP1_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.SLIP2_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.SLIP2_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.SLIP2_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SLIP2_", "double", 0, "slip2, force dependent slip direction 2", "", &ModelSpawnConfig::SLIP2_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SLIP2_", "double", 0, "slip2, force dependent slip direction 2", "", &ModelSpawnConfig::SLIP2_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.SOFT_CFM_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.SOFT_CFM_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.SOFT_CFM_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SOFT_CFM_", "double", 0, "Soft constraint force mixing", "", &ModelSpawnConfig::SOFT_CFM_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SOFT_CFM_", "double", 0, "Soft constraint force mixing", "", &ModelSpawnConfig::SOFT_CFM_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.SOFT_ERP_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.SOFT_ERP_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.SOFT_ERP_ = 0.2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SOFT_ERP_", "double", 0, "Soft error reduction parameter", "", &ModelSpawnConfig::SOFT_ERP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SOFT_ERP_", "double", 0, "Soft error reduction parameter", "", &ModelSpawnConfig::SOFT_ERP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.KP_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.KP_ = 1000000000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.KP_ = 1000000000000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("KP_", "double", 0, "Dynamically stiffness-equivalent coefficient for contact joints", "", &ModelSpawnConfig::KP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("KP_", "double", 0, "Dynamically stiffness-equivalent coefficient for contact joints", "", &ModelSpawnConfig::KP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.KD_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.KD_ = 100000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.KD_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("KD_", "double", 0, "Dynamically damping-equivalent coefficient for contact joints", "", &ModelSpawnConfig::KD_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("KD_", "double", 0, "Dynamically damping-equivalent coefficient for contact joints", "", &ModelSpawnConfig::KD_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MINDEPTH_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MINDEPTH_ = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MINDEPTH_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("MINDEPTH_", "double", 0, "Minimum allowable depth before contact correction impulse is applied", "", &ModelSpawnConfig::MINDEPTH_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("MINDEPTH_", "double", 0, "Minimum allowable depth before contact correction impulse is applied", "", &ModelSpawnConfig::MINDEPTH_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MAXVEL_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MAXVEL_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MAXVEL_ = 0.01;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("MAXVEL_", "double", 0, "Maximum contact correction velocity truncation term", "", &ModelSpawnConfig::MAXVEL_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("MAXVEL_", "double", 0, "Maximum contact correction velocity truncation term", "", &ModelSpawnConfig::MAXVEL_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.VELDECAYLINEAR_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.VELDECAYLINEAR_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.VELDECAYLINEAR_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("VELDECAYLINEAR_", "double", 0, "Velocity decay linear term", "", &ModelSpawnConfig::VELDECAYLINEAR_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("VELDECAYLINEAR_", "double", 0, "Velocity decay linear term", "", &ModelSpawnConfig::VELDECAYLINEAR_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.VELDECAYANGULAR_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.VELDECAYANGULAR_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.VELDECAYANGULAR_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("VELDECAYANGULAR_", "double", 0, "Velocity decay angular term", "", &ModelSpawnConfig::VELDECAYANGULAR_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("VELDECAYANGULAR_", "double", 0, "Velocity decay angular term", "", &ModelSpawnConfig::VELDECAYANGULAR_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.click_to_spawn_model = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.click_to_spawn_model = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.click_to_spawn_model = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<bool>("click_to_spawn_model", "bool", 0, "Click here to spawn model", "", &ModelSpawnConfig::click_to_spawn_model)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<bool>("click_to_spawn_model", "bool", 0, "Click here to spawn model", "", &ModelSpawnConfig::click_to_spawn_model)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.DEGREESRAMP = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.DEGREESRAMP = 180.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.DEGREESRAMP = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("DEGREESRAMP", "double", 0, "Degrees of inclination of the ramp", "", &ModelSpawnConfig::DEGREESRAMP)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("DEGREESRAMP", "double", 0, "Degrees of inclination of the ramp", "", &ModelSpawnConfig::DEGREESRAMP)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MURAMP_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MURAMP_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MURAMP_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("MURAMP_", "double", 0, "mu, Coefficient of friction", "", &ModelSpawnConfig::MURAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("MURAMP_", "double", 0, "mu, Coefficient of friction", "", &ModelSpawnConfig::MURAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MU2RAMP_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MU2RAMP_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MU2RAMP_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("MU2RAMP_", "double", 0, "mu2, Second coefficient of friction", "", &ModelSpawnConfig::MU2RAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("MU2RAMP_", "double", 0, "mu2, Second coefficient of friction", "", &ModelSpawnConfig::MU2RAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FDIR1XRAMP_ = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FDIR1XRAMP_ = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FDIR1XRAMP_ = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<int>("FDIR1XRAMP_", "int", 0, "fdir1 X, direction of mu1 in the collision local reference frame", "", &ModelSpawnConfig::FDIR1XRAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<int>("FDIR1XRAMP_", "int", 0, "fdir1 X, direction of mu1 in the collision local reference frame", "", &ModelSpawnConfig::FDIR1XRAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FDIR1YRAMP_ = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FDIR1YRAMP_ = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FDIR1YRAMP_ = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<int>("FDIR1YRAMP_", "int", 0, "fdir1 Y, direction of mu1 in the collision local reference frame", "", &ModelSpawnConfig::FDIR1YRAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<int>("FDIR1YRAMP_", "int", 0, "fdir1 Y, direction of mu1 in the collision local reference frame", "", &ModelSpawnConfig::FDIR1YRAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FDIR1ZRAMP_ = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FDIR1ZRAMP_ = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FDIR1ZRAMP_ = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<int>("FDIR1ZRAMP_", "int", 0, "fdir1 Z, direction of mu1 in the collision local reference frame", "", &ModelSpawnConfig::FDIR1ZRAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<int>("FDIR1ZRAMP_", "int", 0, "fdir1 Z, direction of mu1 in the collision local reference frame", "", &ModelSpawnConfig::FDIR1ZRAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.SLIP1RAMP_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.SLIP1RAMP_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.SLIP1RAMP_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SLIP1RAMP_", "double", 0, "slip1, force dependent slip direction 1", "", &ModelSpawnConfig::SLIP1RAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SLIP1RAMP_", "double", 0, "slip1, force dependent slip direction 1", "", &ModelSpawnConfig::SLIP1RAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.SLIP2RAMP_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.SLIP2RAMP_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.SLIP2RAMP_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SLIP2RAMP_", "double", 0, "slip2, force dependent slip direction 2", "", &ModelSpawnConfig::SLIP2RAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SLIP2RAMP_", "double", 0, "slip2, force dependent slip direction 2", "", &ModelSpawnConfig::SLIP2RAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.SOFT_CFMRAMP_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.SOFT_CFMRAMP_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.SOFT_CFMRAMP_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SOFT_CFMRAMP_", "double", 0, "Soft constraint force mixing", "", &ModelSpawnConfig::SOFT_CFMRAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SOFT_CFMRAMP_", "double", 0, "Soft constraint force mixing", "", &ModelSpawnConfig::SOFT_CFMRAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.SOFT_ERPRAMP_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.SOFT_ERPRAMP_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.SOFT_ERPRAMP_ = 0.2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SOFT_ERPRAMP_", "double", 0, "Soft error reduction parameter", "", &ModelSpawnConfig::SOFT_ERPRAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("SOFT_ERPRAMP_", "double", 0, "Soft error reduction parameter", "", &ModelSpawnConfig::SOFT_ERPRAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.KPRAMP_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.KPRAMP_ = 1000000000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.KPRAMP_ = 1000000000000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("KPRAMP_", "double", 0, "Dynamically stiffness-equivalent coefficient for contact joints", "", &ModelSpawnConfig::KPRAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("KPRAMP_", "double", 0, "Dynamically stiffness-equivalent coefficient for contact joints", "", &ModelSpawnConfig::KPRAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.KDRAMP_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.KDRAMP_ = 100000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.KDRAMP_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("KDRAMP_", "double", 0, "Dynamically damping-equivalent coefficient for contact joints", "", &ModelSpawnConfig::KDRAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("KDRAMP_", "double", 0, "Dynamically damping-equivalent coefficient for contact joints", "", &ModelSpawnConfig::KDRAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MINDEPTHRAMP_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MINDEPTHRAMP_ = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MINDEPTHRAMP_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("MINDEPTHRAMP_", "double", 0, "Minimum allowable depth before contact correction impulse is applied", "", &ModelSpawnConfig::MINDEPTHRAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("MINDEPTHRAMP_", "double", 0, "Minimum allowable depth before contact correction impulse is applied", "", &ModelSpawnConfig::MINDEPTHRAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MAXVELRAMP_ = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MAXVELRAMP_ = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MAXVELRAMP_ = 0.01;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("MAXVELRAMP_", "double", 0, "Maximum contact correction velocity truncation term", "", &ModelSpawnConfig::MAXVELRAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<double>("MAXVELRAMP_", "double", 0, "Maximum contact correction velocity truncation term", "", &ModelSpawnConfig::MAXVELRAMP_)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.click_to_spawn_ramp = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.click_to_spawn_ramp = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.click_to_spawn_ramp = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<bool>("click_to_spawn_ramp", "bool", 0, "Click here to spawn ramp model", "", &ModelSpawnConfig::click_to_spawn_ramp)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ModelSpawnConfig::AbstractParamDescriptionConstPtr(new ModelSpawnConfig::ParamDescription<bool>("click_to_spawn_ramp", "bool", 0, "Click here to spawn ramp model", "", &ModelSpawnConfig::click_to_spawn_ramp)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ModelSpawnConfig::AbstractGroupDescriptionConstPtr(new ModelSpawnConfig::GroupDescription<ModelSpawnConfig::DEFAULT, ModelSpawnConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<ModelSpawnConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<ModelSpawnConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<ModelSpawnConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    ModelSpawnConfig __max__;
    ModelSpawnConfig __min__;
    ModelSpawnConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const ModelSpawnConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static ModelSpawnConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &ModelSpawnConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const ModelSpawnConfig &ModelSpawnConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const ModelSpawnConfig &ModelSpawnConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const ModelSpawnConfig &ModelSpawnConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<ModelSpawnConfig::AbstractParamDescriptionConstPtr> &ModelSpawnConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<ModelSpawnConfig::AbstractGroupDescriptionConstPtr> &ModelSpawnConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const ModelSpawnConfigStatics *ModelSpawnConfig::__get_statics__()
  {
    const static ModelSpawnConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = ModelSpawnConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __MODELSPAWNRECONFIGURATOR_H__
