controller_list:
  - name: fake_Panda_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - panda1_joint1
      - panda1_joint2
      - panda1_joint3
      - panda1_joint4
      - panda1_joint5
      - panda1_joint6
      - panda1_joint7
  - name: fake_Hand_controller
    type: $(arg fake_execution_type)
    joints:
      - panda1_finger_joint1
      - panda1_finger_joint2
initial:  # Define initial robot poses per group
  - group: Panda_arm
    pose: Pos1
  - group: Hand
    pose: closed