Panda_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda1_joint1
    - panda1_joint2
    - panda1_joint3
    - panda1_joint4
    - panda1_joint5
    - panda1_joint6
    - panda1_joint7
  gains:
    panda1_joint1:
      p: 16000
      d: 100
      i: 1
      i_clamp: 1
    panda1_joint2:
      p: 15000
      d: 100
      i: 1
      i_clamp: 1
    panda1_joint3:
      p: 14000
      d: 100
      i: 1
      i_clamp: 1
    panda1_joint4:
      p: 13000
      d: 100
      i: 1
      i_clamp: 1
    panda1_joint5:
      p: 12000
      d: 100
      i: 1
      i_clamp: 1
    panda1_joint6:
      p: 11000
      d: 100
      i: 1
      i_clamp: 1
    panda1_joint7:
      p: 10000
      d: 100
      i: 1
      i_clamp: 1
Hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda1_finger_joint1
    - panda1_finger_joint2
  gains:
    panda1_finger_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda1_finger_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
