controller_list:
  - name: Panda_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - panda1_joint1
      - panda1_joint2
      - panda1_joint3
      - panda1_joint4
      - panda1_joint5
      - panda1_joint6
      - panda1_joint7
  - name: Hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - panda1_finger_joint1
      - panda1_finger_joint2