panda_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  gains:
    panda_joint1:
      p: 18000
      d: 100
      i: 1
      i_clamp: 1
    panda_joint2:
      p: 25000
      d: 100
      i: 1
      i_clamp: 1
    panda_joint3:
      p: 18000
      d: 100
      i: 1
      i_clamp: 1
    panda_joint4:
      p: 18000
      d: 100
      i: 1
      i_clamp: 1
    panda_joint5:
      p: 12000
      d: 100
      i: 1
      i_clamp: 1
    panda_joint6:
      p: 7000
      d: 100
      i: 1
      i_clamp: 1
    panda_joint7:
      p: 2000
      d: 100
      i: 1
      i_clamp: 1
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
panda_hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_finger_joint1
    - panda_finger_joint2
  gains:
    panda_finger_joint1:
      p: 150
      d: 1
      i: 1
      i_clamp: 1
    panda_finger_joint2:
      p: 150
      d: 1
      i: 1
      i_clamp: 1
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
